export const PERMISSIONS = {
  ROLE_MANAGE: 'ROLE_MANAGE',
  PROFILE_READ_SELF: 'PROFILE_READ_SELF',
  PROFILE_WRITE_SELF: 'PROFILE_WRITE_SELF',
  CATEGORY_MANAGE: 'CATEGORY_MANAGE',
  PRODUCT_READ: 'PRODUCT_READ',
  PRODUCT_MANAGE: 'PRODUCT_MANAGE',
  TABLE_READ: 'TABLE_READ',
  TABLE_MANAGE: 'TABLE_MANAGE',
  TABLE_QR_ROTATE: 'TABLE_QR_ROTATE',
  BUSINESS_DAY_OPEN: 'BUSINESS_DAY_OPEN',
  BUSINESS_DAY_CLOSE: 'BUSINESS_DAY_CLOSE',
  INVENTORY_READ: 'INVENTORY_READ',
  INVENTORY_OPEN: 'INVENTORY_OPEN',
  INVENTORY_RESTOCK: 'INVENTORY_RESTOCK',
  INVENTORY_GIFT: 'INVENTORY_GIFT',
  INVENTORY_CONSUMPTION: 'INVENTORY_CONSUMPTION',
  INVENTORY_WASTE: 'INVENTORY_WASTE',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  ORDER_CREATE_MANUAL: 'ORDER_CREATE_MANUAL',
  ORDER_READ_OPERATIONAL: 'ORDER_READ_OPERATIONAL',
  ORDER_TRANSITION: 'ORDER_TRANSITION',
  ORDER_CANCEL_EXCEPTION: 'ORDER_CANCEL_EXCEPTION',
  PAYMENT_VERIFY: 'PAYMENT_VERIFY',
  CASH_OPEN: 'CASH_OPEN',
  CASH_CLOSE: 'CASH_CLOSE',
  CASH_READ: 'CASH_READ',
  REPORT_READ: 'REPORT_READ',
  AUDIT_READ: 'AUDIT_READ',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ADMIN_PERMISSIONS: PermissionCode[] = Object.values(PERMISSIONS);

const WORKER_PERMISSIONS: PermissionCode[] = [
  PERMISSIONS.PROFILE_READ_SELF,
  PERMISSIONS.PROFILE_WRITE_SELF,
  PERMISSIONS.PRODUCT_READ,
  PERMISSIONS.TABLE_READ,
  PERMISSIONS.INVENTORY_READ,
  PERMISSIONS.INVENTORY_RESTOCK,
  PERMISSIONS.INVENTORY_GIFT,
  PERMISSIONS.INVENTORY_CONSUMPTION,
  PERMISSIONS.INVENTORY_WASTE,
  PERMISSIONS.ORDER_CREATE_MANUAL,
  PERMISSIONS.ORDER_READ_OPERATIONAL,
  PERMISSIONS.ORDER_TRANSITION,
  PERMISSIONS.PAYMENT_VERIFY,
  PERMISSIONS.CASH_READ,
];

const CUSTOMER_PERMISSIONS: PermissionCode[] = [
  PERMISSIONS.PROFILE_READ_SELF,
  PERMISSIONS.PROFILE_WRITE_SELF,
];

const SYSTEM_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  ADMIN: ADMIN_PERMISSIONS,
  WORKER: WORKER_PERMISSIONS,
  CUSTOMER: CUSTOMER_PERMISSIONS,
};

export function permissionsForRole(codigoRol: string): PermissionCode[] | null {
  return SYSTEM_ROLE_PERMISSIONS[codigoRol] ?? null;
}

export const PERMISSION_LABELS: Record<PermissionCode, string> = {
  ROLE_MANAGE: 'Gestionar roles',
  PROFILE_READ_SELF: 'Consultar perfil propio',
  PROFILE_WRITE_SELF: 'Editar perfil propio',
  CATEGORY_MANAGE: 'Gestionar categorías',
  PRODUCT_READ: 'Consultar productos',
  PRODUCT_MANAGE: 'Gestionar productos',
  TABLE_READ: 'Consultar mesas',
  TABLE_MANAGE: 'Gestionar mesas',
  TABLE_QR_ROTATE: 'Rotar QR de mesas',
  BUSINESS_DAY_OPEN: 'Abrir jornada',
  BUSINESS_DAY_CLOSE: 'Cerrar jornada',
  INVENTORY_READ: 'Consultar inventario',
  INVENTORY_OPEN: 'Inicializar inventario',
  INVENTORY_RESTOCK: 'Reponer inventario',
  INVENTORY_GIFT: 'Registrar regalías',
  INVENTORY_CONSUMPTION: 'Registrar consumo',
  INVENTORY_WASTE: 'Registrar desperdicio',
  INVENTORY_ADJUST: 'Ajustar inventario',
  ORDER_CREATE_MANUAL: 'Crear pedido manual',
  ORDER_READ_OPERATIONAL: 'Consultar pedidos operativos',
  ORDER_TRANSITION: 'Cambiar estado de pedido',
  ORDER_CANCEL_EXCEPTION: 'Cancelar pedido excepcional',
  PAYMENT_VERIFY: 'Verificar pagos',
  CASH_OPEN: 'Abrir caja',
  CASH_CLOSE: 'Cerrar caja',
  CASH_READ: 'Consultar caja',
  REPORT_READ: 'Consultar reportes',
  AUDIT_READ: 'Consultar auditoría',
};
